// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace code_hedgehog_extention_mine
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidcode_hedgehog_extention_minePackageString = "73a7c5cd-049e-44ec-9d38-9d5137d8634a";
        public static Guid guidcode_hedgehog_extention_minePackage = new Guid(guidcode_hedgehog_extention_minePackageString);

        public const string guidcode_hedgehog_extention_minePackageCmdSetString = "c7fe77cc-4ef5-4314-8c05-e575d7d14633";
        public static Guid guidcode_hedgehog_extention_minePackageCmdSet = new Guid(guidcode_hedgehog_extention_minePackageCmdSetString);

        public const string guidImagesString = "2de6616e-5123-48b5-bede-ad946aa95bc9";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "dba336eb-e8e3-4ce0-88f1-9808f1c3f383";
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyToolWindowCommandId = 0x0100;
        public const int cmdidLoginToolWindowCommand = 0x0101;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}